"""Executions API wrapper for DeepOriginClient."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from deeporigin.platform.client import DeepOriginClient

from deeporigin.platform.constants import TERMINAL_STATES
from deeporigin.utils.constants import TOOL_EXECUTION_POST_TIMEOUT_SECONDS


class Executions:
    """Executions API wrapper.

    Provides access to tool execution-related endpoints through the DeepOriginClient.
    """

    def __init__(self, client: DeepOriginClient) -> None:
        """Initialize Executions wrapper.

        Args:
            client: The DeepOriginClient instance to use for API calls.
        """
        self._c = client

    def create(
        self,
        *,
        tool_key: str,
        tool_version: str,
        data: dict,
        timeout: float | None = None,
    ) -> dict:
        """Create (run) an execution of a tool with a specific version.

        Args:
            tool_key: Key of the tool to run.
            tool_version: Version of the tool to run.
            data: Data transfer object (DTO) containing tool execution parameters.
                This is typically generated by the `make_payload` function.
                If "clusterId" is not present, it will be set to the default cluster ID.
            timeout: HTTP timeout in seconds for this request. If None, uses
                ``TOOL_EXECUTION_POST_TIMEOUT_SECONDS`` (120s), since quoting and
                execution creation can exceed the client's default short timeout.

        Returns:
            Dictionary containing the execution response from the API.

        Raises:
            Exception: If the tool execution fails, with error details printed.
        """
        payload = data.copy()

        if "clusterId" not in payload:
            payload["clusterId"] = self._c.clusters.get_default_cluster_id()

        payload["app"] = self._c._app
        payload["session"] = self._c._session

        req_timeout = (
            timeout if timeout is not None else TOOL_EXECUTION_POST_TIMEOUT_SECONDS
        )

        return self._c.post_json(
            f"/tools/{self._c.org_key}/tools/{tool_key}/{tool_version}/executions",
            body=payload,
            timeout=req_timeout,
        )

    def list(
        self,
        *,
        page: int | None = None,
        page_size: int | None = None,
        order: str | None = None,
        tool_key: str | None = None,
    ) -> dict:
        """List tool executions with pagination and filtering.

        Args:
            page: Page number of the pagination (default 0).
            page_size: Page size of the pagination (max 10,000).
            order: Order of the pagination, e.g., "executionId? asc", "completedAt? desc".
            tool_key: Tool key to filter by.

        Returns:
            Dictionary containing paginated execution data.
        """
        params: dict[str, int | str] = {}
        if page is not None:
            params["page"] = page
        if page_size is not None:
            params["pageSize"] = page_size
        if order is not None:
            params["order"] = order

        if tool_key is not None:
            import json

            params["filter"] = json.dumps({"tool": {"toolManifest": {"key": tool_key}}})

        return self._c.get_json(
            f"/tools/{self._c.org_key}/tools/executions",
            params=params if params else None,
        )

    def get(self, execution_id: str) -> dict:
        """Get a tool execution by execution ID.

        Args:
            execution_id: The execution ID to fetch.

        Returns:
            Dictionary containing the tool execution data.
        """
        return self._c.get_json(
            f"/tools/{self._c.org_key}/tools/executions/{execution_id}"
        )

    def cancel(self, execution_id: str) -> None:
        """Cancel a tool execution.

        Args:
            execution_id: The execution ID to cancel.

        Returns:
            None. If the execution is already in a terminal state, returns early.
        """
        data = self.get(execution_id)

        if data.get("status") in TERMINAL_STATES:
            return

        self._c._patch(
            f"/tools/{self._c.org_key}/tools/executions/{execution_id}:cancel"
        )

    def confirm(self, execution_id: str) -> None:
        """Confirm a tool execution.

        Args:
            execution_id: The execution ID to confirm.

        Returns:
            None.
        """
        self._c._patch(
            f"/tools/{self._c.org_key}/tools/executions/{execution_id}:confirm"
        )
