"""Executions API wrapper for DeepOriginClient."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from deeporigin.platform.client import DeepOriginClient

from deeporigin.platform.constants import TERMINAL_STATES
from deeporigin.utils.constants import TOOL_EXECUTION_POST_TIMEOUT_SECONDS


class Executions:
    """Executions API wrapper.

    Provides access to tool execution-related endpoints through the DeepOriginClient.
    """

    def __init__(self, client: DeepOriginClient) -> None:
        """Initialize Executions wrapper.

        Args:
            client: The DeepOriginClient instance to use for API calls.
        """
        self._c = client

    def create(
        self,
        *,
        tool_key: str,
        tool_version: str,
        data: dict,
        timeout: float | None = None,
    ) -> dict:
        """Create (run) an execution of a tool with a specific version.

        Args:
            tool_key: Key of the tool to run.
            tool_version: Version of the tool to run.
            data: Data transfer object (DTO) containing tool execution parameters.
                This is typically generated by the `make_payload` function.
                If "clusterId" is not present, it will be set to the default cluster ID.
            timeout: HTTP timeout in seconds for this request. If None, uses
                ``TOOL_EXECUTION_POST_TIMEOUT_SECONDS`` (120s), since quoting and
                execution creation can exceed the client's default short timeout.

        Returns:
            Dictionary containing the execution response from the API.

        Raises:
            Exception: If the tool execution fails, with error details printed.
        """
        payload = data.copy()

        if "clusterId" not in payload:
            payload["clusterId"] = self._c.clusters.get_default_cluster_id()
        if self._c.project_id is not None:
            payload["projectId"] = self._c.project_id

        payload["app"] = self._c._app
        payload["session"] = self._c._session

        req_timeout = (
            timeout if timeout is not None else TOOL_EXECUTION_POST_TIMEOUT_SECONDS
        )

        return self._c.post_json(
            f"/tools/{self._c.org_key}/tools/{tool_key}/{tool_version}/executions",
            body=payload,
            timeout=req_timeout,
        )

    def list(
        self,
        *,
        page: int | None = None,
        page_size: int | None = None,
        order: str | None = None,
        tool_key: str | None = None,
        session: str | None = None,
    ) -> dict:
        """List tool executions with pagination and filtering.

        Args:
            page: Page number of the pagination (default 0).
            page_size: Page size of the pagination (max 10,000).
            order: Order of the pagination, e.g., "executionId? asc", "completedAt? desc".
            tool_key: Tool key to filter by.
            session: Session identifier to filter by. Returns only executions
                tagged with this session on creation (see ``executions.create``
                where ``payload["session"] = self._c._session``). Without this,
                the endpoint returns all executions the caller can see, not
                just ones from the caller's own client.

        Returns:
            Dictionary containing paginated execution data.
        """
        params: dict[str, int | str] = {}
        if page is not None:
            params["page"] = page
        if page_size is not None:
            params["pageSize"] = page_size
        if order is not None:
            params["order"] = order

        filter_dict: dict = {}
        if tool_key is not None:
            filter_dict["tool"] = {"toolManifest": {"key": tool_key}}
        if session is not None:
            filter_dict["session"] = session

        if filter_dict:
            import json

            params["filter"] = json.dumps(filter_dict)

        return self._c.get_json(
            f"/tools/{self._c.org_key}/tools/executions",
            params=params if params else None,
        )

    def get(self, execution_id: str) -> dict:
        """Get a tool execution by execution ID.

        Args:
            execution_id: The execution ID to fetch.

        Returns:
            Dictionary containing the tool execution data.
        """
        return self._c.get_json(
            f"/tools/{self._c.org_key}/tools/executions/{execution_id}"
        )

    def search(
        self,
        *,
        project_id: str | None = None,
        tool_key: list[str] | str | None = None,
        status: str | None = None,
        extra_props: list[dict[str, Any]] | None = None,
        limit: int | None = None,
        offset: int | None = None,
        select: list[str] | None = None,
        with_total_count: bool = False,
        compute_job_id: str | None = None,
    ) -> dict:
        """Search executions via the data-platform endpoint.

        Unlike :meth:`list` (which hits the tools-service, has no project
        scoping, and returns a DTO shape missing ``project_id`` on most
        rows), this method hits
        ``POST /data-platform/{org}/executions/search`` which:

        - exposes ``project_id`` as a first-class column and applies it as
          a server-side filter when provided,
        - returns rows with snake_case columns (``tool_key``,
          ``started_at``, ``project_id``, ...) and ``tags`` (``app`` +
          ``session``) / ``compute_metadata`` (``userInputs``, ...) as
          nested objects,
        - supports the standard data-platform ``{"props": [...]}`` filter
          grammar with ``eq`` / ``neq`` / ``in`` / ... ops.

        Args:
            project_id: Scope to this project. **Strongly recommended** —
                without it the response spans every execution the caller
                can see.
            tool_key: Equality filter on ``tool_key`` (e.g.
                ``"deeporigin.bulk-docking"``).
            status: Equality filter on ``status`` (e.g. ``"Completed"``,
                ``"Failed"``, ``"Running"``).
            extra_props: Additional filter props appended to the
                built-in ones. Each prop is a dict with
                ``{"column": str, "op": str, "value": Any}``.
            limit: Max rows to return.
            offset: Skip offset.
            select: Columns to select; all columns by default.
            with_total_count: When True, the server returns a total count
                alongside the page (may be slower).

        Returns:
            The raw response dict, typically ``{"data": [...], "meta": {...}}``.
        """
        props: list[dict[str, Any]] = []
        if project_id is not None:
            props.append({"column": "project_id", "op": "eq", "value": project_id})
        if isinstance(tool_key, (list, tuple)):
            props.append({"column": "tool_key", "op": "in", "value": tool_key})
        elif isinstance(tool_key, str) and tool_key:
            props.append({"column": "tool_key", "op": "eq", "value": tool_key})
        if status is not None:
            props.append({"column": "status", "op": "eq", "value": status})
        if compute_job_id is not None:
            props.append({"column": "compute_job_id", "op": "eq", "value": compute_job_id})
        if extra_props:
            props.extend(extra_props)

        body: dict[str, Any] = {"filter": {"props": props}}
        if limit is not None:
            body["limit"] = limit
        if offset is not None:
            body["offset"] = offset
        if select is not None:
            body["select"] = select
        if with_total_count:
            body["with_total_count"] = True

        return self._c.post_json(
            f"/data-platform/{self._c.org_key}/executions/search",
            body=body,
        )

    def from_data_platform(self, data_platform_execution_id: str) -> dict:
        """Get an execution from the data-platform API by its execution identifier.

        This identifier is not the same as the tools-service ``execution_id`` used
        by :meth:`get`.

        Args:
            data_platform_execution_id: Data-platform execution ID (e.g. from search UIs).

        Returns:
            Dictionary containing the execution record from the data platform.
        """
        return self._c.get_json(
            f"/data-platform/{self._c.org_key}/executions/{data_platform_execution_id}"
        )

    def cancel(self, execution_id: str) -> None:
        """Cancel a tool execution.

        Args:
            execution_id: The execution ID to cancel.

        Returns:
            None. If the execution is already in a terminal state, returns early.
        """
        data = self.get(execution_id)

        if data.get("status") in TERMINAL_STATES:
            return

        self._c._patch(
            f"/tools/{self._c.org_key}/tools/executions/{execution_id}:cancel"
        )

    def confirm(self, execution_id: str) -> None:
        """Confirm a tool execution.

        Args:
            execution_id: The execution ID to confirm.

        Returns:
            None.
        """
        self._c._patch(
            f"/tools/{self._c.org_key}/tools/executions/{execution_id}:confirm"
        )
