"""Executions API wrapper for DeepOriginClient."""

from __future__ import annotations

import builtins
from datetime import datetime, timezone
import time
from typing import TYPE_CHECKING, Any

from beartype import beartype

if TYPE_CHECKING:
    from deeporigin.platform.client import DeepOriginClient

from deeporigin.platform.constants import TERMINAL_STATES
from deeporigin.utils.constants import (
    TOOL_EXECUTION_GET_ACCEPT_HEADER,
    TOOL_EXECUTION_POST_TIMEOUT_SECONDS,
)


def _created_after_to_iso_utc(created_after: datetime | str) -> str:
    """Format a lower bound for ``createdAt: {$gt: ...}`` tools list filters.

    Args:
        created_after: Instant or ISO-8601 string (as accepted by the API).

    Returns:
        UTC timestamp string with millisecond precision and ``Z`` suffix,
        matching typical execution DTO ``createdAt`` values.
    """
    if isinstance(created_after, str):
        return created_after
    dt = created_after
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    else:
        dt = dt.astimezone(timezone.utc)
    return dt.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


class Executions:
    """Executions API wrapper.

    Provides access to tool execution-related endpoints through the DeepOriginClient.
    """

    def __init__(self, client: DeepOriginClient) -> None:
        """Initialize Executions wrapper.

        Args:
            client: The DeepOriginClient instance to use for API calls.
        """
        self._c = client

    def create(
        self,
        *,
        tool_key: str,
        tool_version: str,
        data: dict,
        timeout: float | None = None,
    ) -> dict:
        """Create (run) an execution of a tool with a specific version.

        Args:
            tool_key: Key of the tool to run.
            tool_version: Version of the tool to run.
            data: Data transfer object (DTO) containing tool execution parameters.
                This is typically generated by the `make_payload` function.
                If "clusterId" is not present, it will be set to the default cluster ID.
            timeout: HTTP timeout in seconds for this request. If None, uses
                ``TOOL_EXECUTION_POST_TIMEOUT_SECONDS`` (600s), since quoting and
                synchronous execution creation can exceed the client's default
                short timeout (e.g. molprops, protonation, system-prep).
                When ``client.tag`` is set, it is sent as ``tag`` unless the
                caller already included ``tag`` in ``data``. When
                ``client.billing_tag`` is set, it is sent as ``billing`` unless
                the caller already included ``billing`` in ``data``.

        Returns:
            Dictionary containing the execution response from the API.

        Raises:
            Exception: If the tool execution fails, with error details printed.
        """
        payload = data.copy()

        if "clusterId" not in payload:
            payload["clusterId"] = self._c.clusters.get_default_cluster_id()
        if self._c.project_id is not None:
            payload["projectId"] = self._c.project_id

        payload["app"] = self._c._app
        payload["session"] = self._c._session
        if self._c.tag is not None and "tag" not in payload:
            payload["tag"] = self._c.tag
        if (
            getattr(self._c, "billing_tag", None) is not None
            and "billing" not in payload
        ):
            payload["billing"] = self._c.billing_tag

        req_timeout = (
            timeout if timeout is not None else TOOL_EXECUTION_POST_TIMEOUT_SECONDS
        )

        return self._c.post_json(
            f"/tools/{self._c.org_key}/tools/{tool_key}/{tool_version}/executions",
            body=payload,
            timeout=req_timeout,
        )

    def _list_tools_executions_page(
        self,
        *,
        page: int | None,
        page_size: int | None,
        order: str | None = None,
        tool_key: str | None = None,
        session: str | None = None,
        project_id: str | None = None,
        created_after: datetime | str | None = None,
    ) -> Any:
        """Perform one GET for the tools-service executions list URL with query params.

        Args:
            page: Zero-based page index, or ``None`` to omit (server default).
            page_size: Page size query param, or ``None`` to omit.
            order: Sort order string.
            tool_key: Filter by tool manifest key.
            session: Filter by session tag.
            project_id: Filter by project id.
            created_after: Lower bound on ``createdAt``.

        Returns:
            Parsed JSON from the platform (typically ``{"data": [...], "count": n}``).
        """
        params: dict[str, int | str] = {}
        if page is not None:
            params["page"] = page
        if page_size is not None:
            params["pageSize"] = page_size
        if order is not None:
            params["order"] = order

        filter_dict: dict = {}
        if tool_key is not None:
            filter_dict["tool"] = {"toolManifest": {"key": tool_key}}
        if session is not None:
            filter_dict["session"] = session
        if project_id is not None:
            filter_dict["projectId"] = project_id
        if created_after is not None:
            filter_dict["createdAt"] = {"$gt": _created_after_to_iso_utc(created_after)}

        if filter_dict:
            import json

            params["filter"] = json.dumps(filter_dict)

        return self._c.get_json(
            f"/tools/{self._c.org_key}/tools/executions",
            params=params if params else None,
        )

    def _list_tools_executions_fetch_all(
        self,
        *,
        chunk_size: int,
        order: str | None = None,
        tool_key: str | None = None,
        session: str | None = None,
        project_id: str | None = None,
        created_after: datetime | str | None = None,
    ) -> dict[str, Any]:
        """Merge every page of tools execution list results for the given filters.

        Args:
            chunk_size: Rows per request (``pageSize`` query param).
            order: Sort order string.
            tool_key: Filter by tool manifest key.
            session: Filter by session tag.
            project_id: Filter by project id.
            created_after: Lower bound on ``createdAt``.

        Returns:
            ``{"data": [...], "count": <server total>}`` with ``data`` concatenated
            across pages in order.
        """
        current_page = 0
        all_dtos: builtins.list[dict[str, Any]] = []
        total_count = 0

        while True:
            response = self._list_tools_executions_page(
                page=current_page,
                page_size=chunk_size,
                order=order,
                tool_key=tool_key,
                session=session,
                project_id=project_id,
                created_after=created_after,
            )

            if not isinstance(response, dict):
                all_dtos.extend(response if isinstance(response, builtins.list) else [])
                return {"data": all_dtos, "count": len(all_dtos)}

            page_dtos = response.get("data", [])
            all_dtos.extend(page_dtos)
            total_count = response.get("count", 0)

            if total_count > chunk_size:
                if len(page_dtos) < chunk_size:
                    break
                if len(all_dtos) >= total_count:
                    break
                current_page += 1
            else:
                break

        return {"data": all_dtos, "count": total_count}

    def list(
        self,
        *,
        page: int | None = None,
        page_size: int | None = None,
        order: str | None = None,
        tool_key: str | None = None,
        session: str | None = None,
        project_id: str | None = None,
        created_after: datetime | str | None = None,
        fetch_all_pages: bool = False,
    ) -> dict:
        """List tool executions with pagination and filtering.

        Args:
            page: Page number of the pagination (default 0). Ignored when
                ``fetch_all_pages`` is ``True``.
            page_size: Page size of the pagination (max 10,000). When
                ``fetch_all_pages`` is ``True`` and this is ``None``, uses ``1000``.
            order: Order of the pagination, e.g., "executionId? asc", "completedAt? desc".
            tool_key: Tool key to filter by.
            session: Session identifier to filter by. Returns only executions
                tagged with this session on creation (see ``executions.create``
                where ``payload["session"] = self._c._session``). Without this,
                the endpoint returns all executions the caller can see, not
                just ones from the caller's own client.
            project_id: When set, restrict to executions whose root-level
                ``projectId`` matches (same field as in the tools execution
                DTO; may be omitted or null on rows that are not project-scoped).
            created_after: When set, restrict to rows with ``createdAt`` strictly
                after this instant. Passed to the tools-service list filter as
                ``createdAt: {"$gt": "<iso-8601>"}`` (MikroORM operator on the
                entity ``createdAt`` column). Use a timezone-aware
                :class:`~datetime.datetime` or an ISO string such as
                ``2026-05-07T15:13:25.254Z``.
            fetch_all_pages: When ``True``, follow pagination until every row
                for the filter is collected, merge ``data`` in page order, and
                return ``{"data": [...], "count": <total>}``. When ``False``,
                performs a single request using ``page`` / ``page_size``.

        Returns:
            Dictionary containing paginated execution data (or all rows when
            ``fetch_all_pages`` is ``True``).
        """
        if fetch_all_pages:
            chunk_size = page_size if page_size is not None else 1000
            return self._list_tools_executions_fetch_all(
                chunk_size=chunk_size,
                order=order,
                tool_key=tool_key,
                session=session,
                project_id=project_id,
                created_after=created_after,
            )

        return self._list_tools_executions_page(
            page=page,
            page_size=page_size,
            order=order,
            tool_key=tool_key,
            session=session,
            project_id=project_id,
            created_after=created_after,
        )

    def get(self, execution_id: str) -> dict:
        """Get a tool execution by execution ID.

        Requests the tools-service v2.0 execution DTO (``Accept:
        application/json;v=2.0``), which includes the enhanced
        ``progressReport`` tree. Top-level fields such as ``executionId``,
        ``status``, ``userInputs``, and ``jobOutputs`` match the v1 shape
        used elsewhere in this library.

        Args:
            execution_id: The execution ID to fetch.

        Returns:
            Dictionary containing the tool execution data.
        """
        return self._c.get_json(
            f"/tools/{self._c.org_key}/tools/executions/{execution_id}",
            headers={"Accept": TOOL_EXECUTION_GET_ACCEPT_HEADER},
        )

    def search(
        self,
        *,
        project_id: str | None = None,
        tool_key: list[str] | str | None = None,
        status: str | None = None,
        extra_props: list[dict[str, Any]] | None = None,
        limit: int | None = None,
        offset: int | None = None,
        select: list[str] | None = None,
        with_total_count: bool = False,
        compute_job_id: str | None = None,
    ) -> dict:
        """Search executions via the data-platform endpoint.

        Unlike :meth:`list` (tools-service DTO with camelCase ``projectId``;
        use ``list(project_id=...)`` to filter there), this method hits
        ``POST /data-platform/{org}/executions/search`` which:

        - exposes ``project_id`` as a first-class column and applies it as
          a server-side filter when provided,
        - returns rows with snake_case columns (``tool_key``,
          ``started_at``, ``project_id``, ...) and ``tags`` (``app`` +
          ``session``) / ``compute_metadata`` (``userInputs``, ...) as
          nested objects,
        - supports the standard data-platform ``{"props": [...]}`` filter
          grammar with ``eq`` / ``neq`` / ``in`` / ... ops.

        Args:
            project_id: Scope to this project. **Strongly recommended** —
                without it the response spans every execution the caller
                can see.
            tool_key: Equality filter on ``tool_key`` (e.g.
                ``"deeporigin.bulk-docking"``).
            status: Equality filter on ``status`` (e.g. ``"Completed"``,
                ``"Failed"``, ``"Running"``).
            extra_props: Additional filter props appended to the
                built-in ones. Each prop is a dict with
                ``{"column": str, "op": str, "value": Any}``.
            limit: Max rows to return.
            offset: Skip offset.
            select: Columns to select; all columns by default.
            with_total_count: When True, the server returns a total count
                alongside the page (may be slower).

        Returns:
            The raw response dict, typically ``{"data": [...], "meta": {...}}``.
        """
        props: list[dict[str, Any]] = []
        if project_id is not None:
            props.append({"column": "project_id", "op": "eq", "value": project_id})
        if isinstance(tool_key, (list, tuple)):
            props.append({"column": "tool_key", "op": "in", "value": tool_key})
        elif isinstance(tool_key, str) and tool_key:
            props.append({"column": "tool_key", "op": "eq", "value": tool_key})
        if status is not None:
            props.append({"column": "status", "op": "eq", "value": status})
        if compute_job_id is not None:
            props.append(
                {"column": "compute_job_id", "op": "eq", "value": compute_job_id}
            )
        if extra_props:
            props.extend(extra_props)

        body: dict[str, Any] = {"filter": {"props": props}}
        if limit is not None:
            body["limit"] = limit
        if offset is not None:
            body["offset"] = offset
        if select is not None:
            body["select"] = select
        if with_total_count:
            body["with_total_count"] = True

        return self._c.post_json(
            f"/data-platform/{self._c.org_key}/executions/search",
            body=body,
        )

    def from_data_platform(self, data_platform_execution_id: str) -> dict:
        """Get an execution from the data-platform API by its execution identifier.

        This identifier is not the same as the tools-service ``execution_id`` used
        by :meth:`get`.

        Args:
            data_platform_execution_id: Data-platform execution ID (e.g. from search UIs).

        Returns:
            Dictionary containing the execution record from the data platform.
        """
        return self._c.get_json(
            f"/data-platform/{self._c.org_key}/executions/{data_platform_execution_id}"
        )

    def cancel(self, execution_id: str) -> None:
        """Cancel a tool execution.

        Args:
            execution_id: The execution ID to cancel.

        Returns:
            None. If the execution is already in a terminal state, returns early.
        """
        data = self.get(execution_id)

        if data.get("status") in TERMINAL_STATES:
            return

        self._c._patch(
            f"/tools/{self._c.org_key}/tools/executions/{execution_id}:cancel"
        )

    def confirm(
        self,
        execution_id: str,
        *,
        timeout: float | None = None,
        retry: bool = True,
    ) -> dict[str, Any]:
        """Confirm a tool execution.

        Args:
            execution_id: The execution ID to confirm.
            timeout: Optional HTTP timeout in seconds for this request. When
                ``None``, the client's default timeout applies.
            retry: When ``True`` (default), use the client's retry policy for
                transient failures. Set ``False`` for a single attempt.

        Returns:
            Updated execution DTO from the platform (same shape as :meth:`get`).
        """
        patch_kwargs: dict[str, Any] = {}
        if timeout is not None:
            patch_kwargs["timeout"] = timeout
        if not retry:
            patch_kwargs["retry"] = False
        response = self._c._patch(
            f"/tools/{self._c.org_key}/tools/executions/{execution_id}:confirm",
            **patch_kwargs,
        )
        return response.json()

    @beartype
    def wait(
        self,
        executions: str | builtins.list[str],
        *,
        poll_interval: float = 5.0,
        timeout: float | None = None,
    ) -> builtins.list[dict]:
        """Block until every given execution reaches a terminal state.

        Periodically polls the platform via :meth:`get` for each execution
        whose status is not yet in
        :data:`~deeporigin.platform.constants.TERMINAL_STATES`, sleeping
        ``poll_interval`` seconds between polling cycles. Once all executions
        have terminated (or ``timeout`` elapses), returns the latest DTOs in
        the same order as the input.

        Args:
            executions: A single execution ID string, or a list of execution
                ID strings to wait on.
            poll_interval: Seconds to sleep between polling cycles. Must be
                positive. Defaults to ``5.0``.
            timeout: Maximum total seconds to wait. If ``None`` (default),
                waits indefinitely. When set and exceeded before all
                executions terminate, raises :class:`TimeoutError`.

        Returns:
            Latest execution DTOs (one per input), each in a terminal state.

        Raises:
            ValueError: If ``executions`` is empty, ``poll_interval`` is not
                positive, or any execution ID is an empty string.
            TimeoutError: If ``timeout`` is set and elapses before every
                execution reaches a terminal state.
        """
        ids = [executions] if isinstance(executions, str) else list(executions)
        if not ids:
            raise ValueError("executions must be a non-empty list")
        if poll_interval <= 0:
            raise ValueError(f"poll_interval must be positive, got {poll_interval!r}")
        for index, exec_id in enumerate(ids):
            if not exec_id:
                raise ValueError(f"executions[{index}] is an empty string")

        latest: dict[str, dict] = {}
        deadline = time.monotonic() + timeout if timeout is not None else None

        while True:
            pending = self._poll_pending(ids, latest)
            if not pending:
                return [latest[exec_id] for exec_id in ids]

            sleep_for = poll_interval
            if deadline is not None:
                remaining = deadline - time.monotonic()
                if remaining <= 0:
                    raise TimeoutError(
                        f"Timed out after {timeout}s waiting for "
                        f"{len(pending)} of {len(ids)} executions to "
                        f"reach a terminal state: {pending}"
                    )
                sleep_for = min(poll_interval, remaining)
            time.sleep(sleep_for)

    def _poll_pending(
        self,
        ids: builtins.list[str],
        latest: dict[str, dict],
    ) -> builtins.list[str]:
        """Refresh non-terminal executions and return those still pending.

        Args:
            ids: Execution IDs to inspect (order preserved).
            latest: Cache of the most recent DTO per execution ID; updated
                in place for any execution that gets re-polled.

        Returns:
            IDs whose latest status is not yet in
            :data:`~deeporigin.platform.constants.TERMINAL_STATES`.
        """
        pending: builtins.list[str] = []
        for exec_id in ids:
            cached = latest.get(exec_id)
            if cached is not None and cached.get("status") in TERMINAL_STATES:
                continue
            dto = self.get(exec_id)
            latest[exec_id] = dto
            if dto.get("status") not in TERMINAL_STATES:
                pending.append(exec_id)
        return pending
