name: Run Level 1 Tests

on:
  pull_request:
    paths:
      - "**/*.py"
  workflow_dispatch:
  workflow_call:
    inputs:
      env:
        description: "Target environment"
        type: string
        required: true

jobs:
  level-1-tests:
    runs-on: ubuntu-latest
    environment: ${{ matrix.env }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
        env: ${{ fromJSON( ((github.event_name == 'workflow_call' || github.event_name == 'release') && inputs.env != '') && format('["{0}"]', inputs.env) || '["dev","staging","prod"]' ) }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: deeporiginbio/do-dd-client
          ref: ${{ github.event_name == 'release' && 'main' || github.ref }}
          token: ${{ github.event_name == 'release' && secrets.CI_BOT_GH_PAT || secrets.GITHUB_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.5.27"

      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}

      - name: Set environment variables
        run: |
          echo "DEEPORIGIN_ORG_KEY=deeporigin" >> "$GITHUB_ENV"
          echo "DEEPORIGIN_ENV=${{ matrix.env }}" >> "$GITHUB_ENV"
          if [ "${{ matrix.env }}" = "prod" ]; then
            echo "DEEPORIGIN_TOKEN=${{ secrets.DEEPORIGIN_TOKEN_PROD }}" >> "$GITHUB_ENV"
          elif [ "${{ matrix.env }}" = "staging" ]; then
            echo "DEEPORIGIN_TOKEN=${{ secrets.DEEPORIGIN_TOKEN_STAGING }}" >> "$GITHUB_ENV"
          elif [ "${{ matrix.env }}" = "dev" ]; then
            echo "DEEPORIGIN_TOKEN=${{ secrets.DEEPORIGIN_TOKEN_DEV }}" >> "$GITHUB_ENV"
          fi

      - name: Install dependencies
        run: uv sync --extra test --extra tools --extra plots --extra core

      - name: "runing level 1 tests"
        run: uv run pytest --env ${{ matrix.env }} -k lv1
