name: Test Functions 

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Target environment"
        type: choice
        required: true
        default: prod
        options: [dev, staging, prod]
  workflow_call:
    inputs:
      env:
        description: "Target environment"
        type: string
        required: true

  # Run every day
  schedule:
    - cron: "0 6 * * *"

  # Run on changes to Python files in src/functions/
  push:
    paths:
      - 'src/functions/**/*.py'

jobs:
  test-functions-on-environment:
    environment: ${{ inputs.env || 'prod' }}
    runs-on: ubuntu-latest
    env:
      DO_ENV: ${{ inputs.env || 'prod' }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: deeporiginbio/do-dd-client
          ref: ${{ github.event_name == 'release' && 'main' || github.ref }}
          token: ${{ github.event_name == 'release' && secrets.CI_BOT_GH_PAT || secrets.GITHUB_TOKEN }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.5.27"
      
      - name: Set up Python
        run: uv python install
      - name: Select env
        env:
          TARGET_ENV: ${{ inputs.env || 'prod' }}
          TOKEN_PROD: ${{ secrets.DO_AUTH_TOKEN_PROD }}
          TOKEN_STAGING: ${{ secrets.DO_AUTH_TOKEN_STAGING }}
          TOKEN_DEV: ${{ secrets.DO_AUTH_TOKEN_DEV }}
        run: |
          AUTH_TOKEN_VAR=$(python3 scripts/get_env_var_name.py access_token)
          ORG_KEY_VAR=$(python3 scripts/get_env_var_name.py org_key)
          ENV_VAR=$(python3 scripts/get_env_var_name.py env)
          echo "${ORG_KEY_VAR}=deeporigin" >> "$GITHUB_ENV"
          echo "${ENV_VAR}=${TARGET_ENV}" >> "$GITHUB_ENV"
          if [ "$TARGET_ENV" = "prod" ]; then
            echo "${AUTH_TOKEN_VAR}=${TOKEN_PROD}" >> "$GITHUB_ENV"
          elif [ "$TARGET_ENV" = "staging" ]; then
            echo "${AUTH_TOKEN_VAR}=${TOKEN_STAGING}" >> "$GITHUB_ENV"
          elif [ "$TARGET_ENV" = "dev" ]; then
            echo "${AUTH_TOKEN_VAR}=${TOKEN_DEV}" >> "$GITHUB_ENV"
          fi
      - name: Install dependencies
        run: uv sync --extra tools --extra test --extra plots --extra core


      - name: Run tests against a live instance
        env:
          TARGET_ENV: ${{ inputs.env || 'prod' }}
        run: uv run pytest -v -s --log-cli-level=ERROR -k test_functions --env "$TARGET_ENV"
