name: Test Functions 

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Target environment"
        type: choice
        required: true
        default: prod
        options: [dev, staging, prod]
  workflow_call:
    inputs:
      env:
        description: "Target environment"
        type: string
        required: true

  # Run every day
  schedule:
    - cron: "0 6 * * *"

  # Run on changes to Python files in src/functions/
  push:
    paths:
      - 'src/functions/**/*.py'

jobs:
  test-functions-on-environment:
    environment: ${{ inputs.env || 'prod' }}
    runs-on: ubuntu-latest
    env:
      DEEPORIGIN_ENV: ${{ inputs.env || 'prod' }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: deeporiginbio/do-dd-client
          ref: ${{ github.event_name == 'workflow_call' && 'main' || github.ref }}
          token: ${{ github.event_name == 'workflow_call' && secrets.CI_BOT_GH_PAT || secrets.GITHUB_TOKEN }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.5.27"
      
      - name: Set up Python
        run: uv python install
      - name: Select env
        run: |
          ENV="${{ inputs.env || 'prod' }}"
          echo "DEEPORIGIN_ORG_KEY=deeporigin" >> "$GITHUB_ENV"
          if [ "$ENV" = "prod" ]; then
            echo "DEEPORIGIN_TOKEN=${{ secrets.DEEPORIGIN_TOKEN_PROD }}" >> "$GITHUB_ENV"
          elif [ "$ENV" = "staging" ]; then
            echo "DEEPORIGIN_TOKEN=${{ secrets.DEEPORIGIN_TOKEN_STAGING }}" >> "$GITHUB_ENV"
          elif [ "$ENV" = "dev" ]; then
            echo "DEEPORIGIN_TOKEN=${{ secrets.DEEPORIGIN_TOKEN_DEV }}" >> "$GITHUB_ENV"
          fi

      - name: Set environment variables for Client
        run: |
          echo "DEEPORIGIN_ENV=${{ inputs.env || 'prod' }}" >> "$GITHUB_ENV"
      - name: Install dependencies
        run: uv sync --extra tools --extra test --extra plots --extra core


      - name: Run tests against a live instance
        run: uv run pytest -v -s --log-cli-level=ERROR -k test_functions --env "${{ inputs.env || 'prod' }}"
