name: Run ABFE

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Target environment"
        type: choice
        required: true
        default: prod
        options: [dev, staging, prod]

jobs:
  run-abfe:
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest
    env:
      DEEPORIGIN_ENV: ${{ inputs.env }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.5.27"
      
      - name: Set up Python
        run: uv python install
      
      - name: Select API token
        run: |
          if [ "${{ inputs.env }}" = "prod" ]; then
            echo "DEEPORIGIN_TOKEN=${{ secrets.DEEPORIGIN_TOKEN_PROD }}" >> "$GITHUB_ENV"
          elif [ "${{ inputs.env }}" = "staging" ]; then
            echo "DEEPORIGIN_TOKEN=${{ secrets.DEEPORIGIN_TOKEN_STAGING }}" >> "$GITHUB_ENV"
          elif [ "${{ inputs.env }}" = "dev" ]; then
            echo "DEEPORIGIN_TOKEN=${{ secrets.DEEPORIGIN_TOKEN_DEV }}" >> "$GITHUB_ENV"
          fi

      - name: Set environment variables for Client
        run: |
          echo "DEEPORIGIN_ORG_KEY=deeporigin" >> "$GITHUB_ENV"
          echo "DEEPORIGIN_ENV=${{ inputs.env }}" >> "$GITHUB_ENV"
      
      - name: Install dependencies
        run: uv sync --extra tools --extra test --extra plots --extra core

      - name: Run ABFE script
        run: uv run tests/run_abfe.py
