name: Test build of Documentation

on:
  pull_request:
    paths:
      - 'docs/**'


jobs:

  build-docs:
    runs-on: ubuntu-latest
    environment:
      name: docs

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.5.27"

      - name: Set up Python
        run: uv python install 3.10

      - name: Build docs and check for errors
        run: bash scripts/build_docs.sh
